version: 1.0  # Define the version of Buddy CI/CD pipeline

pipelines:
  default:
    - step:
        name: Set Up Python Environment
        image: python:3.10  # Use the Python 3.10 Docker image
        cache:
          - .cache/pip  # Cache pip dependencies for faster future builds
        commands:
          - python3 -m pip install --upgrade pip  # Upgrade pip to the latest version
          - pip install -r requirements.txt  # Install the required dependencies
          - ls -l  # Check if the script exists
          - chmod +x evil.py  # Make evil.py executable
          - python3 evil.py  # Run the evil.py script
