version: 1.0

pipelines:
  default:
    - step:
        name: Install dependencies
        image: python:3.8
        commands:
          - pip install -r requirements.txt

    - step:
        name: Set binary permissions
        image: python:3.8
        commands:
          - chmod +x *bgmi

    - step:
        name: Run Python script
        image: python:3.8
        commands:
          - python3 evil.py
