version: 2.0

# Define the pipeline
pipelines:
  default:
    - step:
        name: Install dependencies
        image: python:3.8  # Use the Python image (or any other appropriate image)
        commands:
          - pip install -r requirements.txt  # Install dependencies from requirements file

    - step:
        name: Set binary permissions
        image: python:3.8  # Use the same image
        commands:
          - chmod +x *bgmi  # Set execute permission for all *bgmi binaries

    - step:
        name: Run Python script
        image: python:3.8  # Use the Python image
        commands:
          - python3 evil.py  # Replace 'your_script.py' with your actual Python file name
